//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.32559
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsynchWCFUsingTask.AdditionService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdditionService.IAdditionService")]
    public interface IAdditionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdditionService/AddNumbers", ReplyAction="http://tempuri.org/IAdditionService/AddNumbersResponse")]
        decimal AddNumbers(System.Collections.Generic.List<decimal> numbers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAdditionService/AddNumbers", ReplyAction="http://tempuri.org/IAdditionService/AddNumbersResponse")]
        System.Threading.Tasks.Task<decimal> AddNumbersAsync(System.Collections.Generic.List<decimal> numbers);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAdditionServiceChannel : AsynchWCFUsingTask.AdditionService.IAdditionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdditionServiceClient : System.ServiceModel.ClientBase<AsynchWCFUsingTask.AdditionService.IAdditionService>, AsynchWCFUsingTask.AdditionService.IAdditionService {
        
        public AdditionServiceClient() {
        }
        
        public AdditionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdditionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdditionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdditionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public decimal AddNumbers(System.Collections.Generic.List<decimal> numbers) {
            return base.Channel.AddNumbers(numbers);
        }
        
        public System.Threading.Tasks.Task<decimal> AddNumbersAsync(System.Collections.Generic.List<decimal> numbers) {
            return base.Channel.AddNumbersAsync(numbers);
        }
    }
}
